### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by akva2**
- create test-suite target for tests added using sattelite macros
- make sure to set the flag needed for dynamic boost::test for relevant targets

### CODE REVIEW

**Comment by akva2** [comment]
this fixes build errors in opm-core (at least). tests did not have the correct HAVE_DYNAMIC_BOOST_TEST due to cache issues.

**Comment by atgeirr** [comment]
I am not sure how I should test this? The problem I had went away upon clearing the build dir, and I cannot get it back to see if I could have avoided it with this patch.

**Comment by akva2** [comment]
bit hard to test yes.  the core of the issue was that HAVE_DYNAMIC_BOOST_TEST somehow (i didn't track it down) ended up with a blank value in the cache. this inhibited the run of check_cxx_source_compiles() which is used to determine whether boost::test is a .so or not. by always unsetting it in the cache, we are certain it will get executed. 

additionally i changed it to check the variable and not its contents in some ifs(), mostly for good practice.

**Comment by atgeirr** [comment]
I have verified that this works for me (tested opm-parser and opm-core), so I'll merge.

**Pull request merged**
