### PR TITLE
Look for python module in ERT

### PR DESCRIPTION
**Pull request by akva2**
This looks for the python module of ERT. Will be used for regression tests in opm-autodiff.

### CODE REVIEW

**Comment by atgeirr** [comment]
I assume it will be required, my question is therefore: is the python module built by default in ert?

**Comment by akva2** [comment]
it is not. you have to pass -DBUILD_PYTHON=1

**Comment by akva2** [comment]
and it's not strictly required, as in the tests are skipped if ert is built without python support (see other pr).

**Comment by joakim-hove** [comment]
The defaults in the ert build system are designed so that opm users/developers can use the defaults, would be happy to change the Python default if that is wanted.

**Comment by atgeirr** [comment]
> The defaults in the ert build system are designed so that opm users/developers can use the defaults, would be happy to change the Python default if that is wanted

Sounds good!

> which in turn requires shared libraries for ERT

... but will this hurt anyone? I think we build shared libs by default, too, don't we?

**Comment by akva2** [comment]
nah won't hurt. it just bit me since i use statics locally for my own reasons.

**Comment by atgeirr** [comment]
Then I am all in favour! But I cannot really review the technical details of this.

**Comment by akva2** [comment]
no problem, i'll execute my maintainer rights. it cannot regress anything so i'll merge.

**Pull request merged**
