### PR TITLE
Fix opm add test regressions

### PR DESCRIPTION
**Pull request by andlaus**
the motivation for this is to fix the testing regressions seen by eWoms by switching to opm_add_test(); cf

http://www.opm-project.org/CDash/index.php?project=eWoms

it also requires the corresponding PR for eWoms to be merged. (whoever merges the opm-cmake PR should please also merge the one for eWoms.)

the meat of this PR is in the first patch (where I also tried to extend the comments for the macro considerably)

### CODE REVIEW

**Comment by akva2** [comment]
if this is merged we have to change parser. i chose to do it this way around and specify WORKING_DIRECTORY in ewoms since that's the 'active' choice.

**Comment by akva2** [comment]
also i really don't like the dummies. just for the record (i didn't remove by accident).

**Comment by andlaus** [comment]
> if this is merged we have to change parser. i chose to do it this way around and specify WORKING_DIRECTORY in ewoms since that's the 'active' choice.

I thought that you did this for a purpose, but I'm pretty sure setting it to the source directory is not a very good idea: besides the possibility that the source dir is not writable, it could be that multiple instances of ctest are running at the same time (think on release vs debug builds on a multi-core machine). this might lead to pretty ugly race conditions if the tests care about their output.

> also i really don't like the dummies. just for the record (i didn't remove by accident).

I don't like them either. I just haven't figured out a better way to tell ctest "I know the test but skip it for some reason". (also, silently ignoring the test is even worse than the dummy IMO.) If you know a better was to achieve this, I'm more than happy to hear about it.

**Comment by akva2** [comment]
we disagree that most tests writes data files. your (regression) tests does, most unit tests do not. i pretty certain that there will be more confusion if peeps can't rely on input data paths blindly.

**Comment by andlaus** [comment]
> we disagree that most tests writes data files. your (regression) tests does, most unit tests do not. i pretty certain that there will be more confusion if peeps can't rely on input data paths blindly.

isn't the default to copy the data files to the build directory if the tests are specified using `CMakeLists_files.txt`? opm-parser probably a bad example because it a quite odd beast when it comes to its use of the build system. (I know, eWoms is also odd.)

(That said, I don't mind too much to change the default back to the source directory or to use the same trick as with the test driver to make it configurable, but since your the build system maintainer you'll have to be prepared to deal with users who fall on their nose because of this ;))

**Comment by akva2** [comment]
yes, for those tests we copy each satellites and their data to their own directory, see OpmSatellites macro opm_compile_satellites. ewoms should ideally be moved to those macros in the long run since these are satellite-type tests. but since it didn't fit either bill, it's currently relient on opm_add_test being more involved than i originally anticipated.

**Comment by andlaus** [comment]
> but since it didn't fit either bill, it's currently relient on opm_add_test being more involved than i originally anticipated.

I know. When I wrote this, it started out pretty simple too, but it gained complexity because I did not want to have all this code directly in `CMakeLists.txt` but I wanted all these features, in particular checking that the results are still correct and CDash showing which tests have been skipped.

Anyway, would you merge the PR if the default working directory is changed back to the source dir?

**Comment by akva2** [comment]
yes.

**Comment by andlaus** [comment]
fixed.

**Comment by akva2** [comment]
thanks.

**Pull request merged**
