### PR TITLE
add opm-material to the prerequisites of opm-core

### PR DESCRIPTION
**Pull request by andlaus**
this is required for OPM/opm-core#834

### CODE REVIEW

**Comment by andlaus** [comment]
note that this PR here can be merged before OPM/opm-core#834 without causing havoc. (people only need to have opm-material available to compile opm-core.)

**Comment by akva2** [comment]
Would you mind updating debian/control to avoid potential confusion. It lists opm-core for some reason.

-------- Opprinnelig melding --------
Fra: Andreas Lauser <notifications@github.com>
Dato: 28.07.2015 18.16 (GMT+01:00)
Til: OPM/opm-cmake <opm-cmake@noreply.github.com>
Emne: [opm-cmake] add opm-material to the prerequisites of opm-core (#27)


this is required for OPM/opm-core#834<https://github.com/OPM/opm-core/pull/834>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/OPM/opm-cmake/pull/27

Commit Summary

  *   add opm-material to the prerequisites of opm-core

File Changes

  *   M cmake/Modules/opm-core-prereqs.cmake<https://github.com/OPM/opm-cmake/pull/27/files#diff-0> (2)

Patch Links:

  *   https://github.com/OPM/opm-cmake/pull/27.patch
  *   https://github.com/OPM/opm-cmake/pull/27.diff

**Comment by akva2** [comment]
In opm-material that is..

-------- Opprinnelig melding --------
Fra: Andreas Lauser <notifications@github.com>
Dato: 28.07.2015 18.16 (GMT+01:00)
Til: OPM/opm-cmake <opm-cmake@noreply.github.com>
Emne: [opm-cmake] add opm-material to the prerequisites of opm-core (#27)


this is required for OPM/opm-core#834<https://github.com/OPM/opm-core/pull/834>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/OPM/opm-cmake/pull/27

Commit Summary

  *   add opm-material to the prerequisites of opm-core

File Changes

  *   M cmake/Modules/opm-core-prereqs.cmake<https://github.com/OPM/opm-cmake/pull/27/files#diff-0> (2)

Patch Links:

  *   https://github.com/OPM/opm-cmake/pull/27.patch
  *   https://github.com/OPM/opm-cmake/pull/27.diff

**Comment by andlaus** [comment]
ok, done, thanks.

BTW: are the dependencies listed in the control file recursive? if so, most of them could be removed from the opm-material control file because they are only used by ERT or opm-parser...

**Comment by akva2** [comment]
Binaries are transitional, headers are not. If none of those are used in templates we might be able to strip some of them off.

**Comment by andlaus** [comment]
I suppose I'm too stupid to get what you want to say: IIRC e.g. the test for the fluid-matrix interactions needs to link to libopmparser if opm-parser was found. does the build control file thus need to specify everything which is needed by opm-parser or is it sufficient to specify opm-parser as a build-time dependency?

**Comment by akva2** [comment]
If opm-parser encapsulates its dependencies in the .so they are autoresolved due to shared objects recording their external dependencies (static is different). But if opm-parser uses some e.g. ert code in some of its headers (ie includes some ert header in one of its headers), you need the ert headers to be able to use that part of opm-parser in opm-material. Since opm is riddled with templates the chance of this is very high. Instead of wasting time trying to minimize build deps, an effort that would likely be continuous i have saved time. Remember these are *build time deps* - runtime deps are resolved automagically through mechanism described above. So the only consequence is a very minor extra install time for the build chroot.

-------- Opprinnelig melding --------
Fra: Andreas Lauser <notifications@github.com>
Dato: 28.07.2015 20.37 (GMT+01:00)
Til: OPM/opm-cmake <opm-cmake@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [opm-cmake] add opm-material to the prerequisites of opm-core (#27)


I suppose I'm too stupid to get what you want to say: IIRC e.g. the test for the fluid-matrix interactions needs to link to libopmparser if opm-parser was found. does the build control file thus need to specify everything which is needed by opm-parser or is it sufficient to specify opm-parser as a build-time dependency?

**Comment by andlaus** [comment]
ok. thanks for the explaination. does there happen to be a mistake in your previous comment? (i.e., didn't you mean that the headers are transitional, while binaries are there to stay?

**Comment by akva2** [comment]
No i meant what i wrote. Transitional = 'carries over'. As in there to stay in your terms.

**Comment by andlaus** [comment]
ah, ok.

**Comment by bska** [comment]
> Transitional = 'carries over'

I think you mean "transitive" here.

**Pull request merged**
